### PR TITLE
Development

### PR DESCRIPTION
**Pull request by RobinSoubry**

### CODE REVIEW

**Comment by RobinSoubry** [comment]
@justincadburywong: Hi Justin, just a though: If we now merge to master, we fully lose the 'clean' Sinatra Skeleton right? … Isn't it better to de-branch away from development and keep master clean?

@davidthegreat @mchaparr0

**Comment by justincadburywong** [comment]
That's actually a good point, and totally fine. If you merge up to the
development branch, I'll pull from there when I get home and create a
feature branch off of that

**Comment by RobinSoubry** [comment]
Ok, we'll commit our changes and start working on new feature branches too. This way, development stays clean when you pull it.

**Comment by justincadburywong** [comment]
Also, I was thinking it would be a good idea to make a new branch off of
the master called 'skeleton' that is just that, so when we merge our
compete project to master, we'll still have a skeleton for other projects

**Comment by RobinSoubry** [comment]
I don't really know how to do this.
Can you do it or tell us how to?

**Comment by justincadburywong** [comment]
Yes!  Before you push to github, on local repo checkout master, then
checkout -b skeleton.  It creates a new branch from master.  You can
checkout your development branch after, and push everything up

**Comment by justincadburywong** [comment]
alas, when i cloned the repo from your freshly merged development branch,
all i got was the master, so i think we MUST merge to master in order for
the clone to work.  i'll keep it as is for now, but i will also create a
seperate branch from the old master.  because i'm not going to be using any
files in the development branch, i don't think we'll have a merge conflict
tomorrow when we combine our work.

**Pull request merged**
